-- Drop constraints first
ALTER TABLE Late_Fees DROP CONSTRAINT IF EXISTS FK__Late_Fees__membe__70DDC3D8;
ALTER TABLE Late_Fees DROP CONSTRAINT IF EXISTS FK__Late_Fees__trans__71D1E811;
ALTER TABLE Transactions DROP CONSTRAINT IF EXISTS FK__Transactions__memb__72C60C4A;
ALTER TABLE Transactions DROP CONSTRAINT IF EXISTS FK__Transactions__movi__73B4E4F6;
ALTER TABLE Movie_Providers DROP CONSTRAINT IF EXISTS FK__Movie_Providers__movi__74A3CBFB;
ALTER TABLE Movie_Providers DROP CONSTRAINT IF EXISTS FK__Movie_Providers__prov__7593B1DE;
ALTER TABLE Favorites DROP CONSTRAINT IF EXISTS FK__Favorites__user__768F439A;
ALTER TABLE Favorites DROP CONSTRAINT IF EXISTS FK__Favorites__movi__777C4178;
ALTER TABLE Watchlist DROP CONSTRAINT IF EXISTS FK__Watchlist__user__786B292E;
ALTER TABLE Watchlist DROP CONSTRAINT IF EXISTS FK__Watchlist__movi__795B1C56;
ALTER TABLE Reviews DROP CONSTRAINT IF EXISTS FK__Reviews__user__7A4A1C1D;
ALTER TABLE Reviews DROP CONSTRAINT IF EXISTS FK__Reviews__movi__7B3A11F3;
ALTER TABLE Movie_Actors DROP CONSTRAINT IF EXISTS FK__Movie_Actors__movi__7C2A1E33;
ALTER TABLE Movie_Actors DROP CONSTRAINT IF EXISTS FK__Movie_Actors__acto__7D1A1F99;
ALTER TABLE Movies DROP CONSTRAINT IF EXISTS FK__Movies__genre__7E0A221A;
ALTER TABLE Members DROP CONSTRAINT IF EXISTS FK__Members__user__7EF027D5;
GO

-- Drop tables if they exist
DROP TABLE IF EXISTS Late_Fees;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Movie_Providers;
DROP TABLE IF EXISTS Streaming_Providers;
DROP TABLE IF EXISTS Favorites;
DROP TABLE IF EXISTS Watchlist;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Movie_Actors;
DROP TABLE IF EXISTS Actors;
DROP TABLE IF EXISTS Movies;
DROP TABLE IF EXISTS Genres;
DROP TABLE IF EXISTS Members;
DROP TABLE IF EXISTS Users;
GO